### PR TITLE
RSS Feed for Events in Stashboard

### PR DESCRIPTION
**Pull request by vmdx**
- Configurable RSS feed (number of events to publish) at the URL `/rss`
- UI button that links to RSS feed in the button group on the top right of the main page
- Test suite for RSS feed syntax / structure

### CODE REVIEW

**Comment by kyleconroy** [comment]
@VMDX Great start. According to the [RSS 2.0 spec](http://cyber.law.harvard.edu/rss/rss.html#hrelementsOfLtitemgt), you have some illegal elements in your `item` element. The item element should look like this instead.

``` xml
<item>
  <title>[Account Portal - Down] Things are going badly</title>
  <description>Things are going badly</description>
  <link>http://localhost:8084/services/account-portal</link>
  <category>account-portal</category>
  <pubDate>Tue, 15 May 2012 16:07:42 GMT</pubDate>
  <guid>http://localhost:8084/api/v1/services/account-portal/events/ag10d2lsaW8tc3RhdHVzcg0LEgVFdmVudBjR4g4M</guid>
</item>
```

The guid should point to the url for the event in the API. This link will always be unique.

The pubDate needs to be in RFC882 format. Use the `wsgiref.handlers.format_date_time` function on the datetime objects

**Comment by kyleconroy** [comment]
Also the correct content type for rss feeds is **application/rss+xml** [Source](http://stackoverflow.com/questions/595616/what-is-the-correct-mime-type-to-use-for-an-rss-feed)

**Comment by vmdx** [comment]
Thanks for clarifying that as the definitive RSS 2.0 spec, will do. Thanks also for the tip on `wsgiref.handlers.format_date_time`.

**Comment by vmdx** [comment]
A little bit concerned about the hardcoded 'api/v1/services/', but there doesn't seem to be a defined place for the current version of the API in the source, aside from `valid_version`, but that's a verification, not a definition.

**Comment by kyleconroy** [comment]
Yeah, I would ok with hardcoding it for now

**Comment by kyleconroy** [comment]
If the message has an & in it, I believe your current code will break. Instead of creating the XML document using a template, it's probably a better idea to use ElementTree.

**Comment by vmdx** [comment]
I'm doing some reading on RSS 2.0 and trying to find if HTML entities (i.e., apostrophes as `&#39;`) are allowed. The templating engine converts things like & to `&amp;` as shown [in this reference](http://www.w3schools.com/tags/ref_entities.asp), but for the ISO-8859-1 symbols and characters, we get gibberish like `Â¥Â¨Å“âˆ‘Â´Ã`.

I'll give ElementTree construction a try, but man, so much less fun than writing a template... :(

**Comment by vmdx** [comment]
RSS special characters are now all numbered entities, now that we are using `xml.etree.ElementTree` to generate the XML.

For example, `¥¨œ∑´æ` turns into `<description>&#165;&#168;&#339;&#8721;&#180;&#230;</description>`.

**Comment by vmdx** [comment]
Hold off on this for now - new branch incoming soon with feeds for each service, and ability to post into a configured Twitter account.

**Comment by kyleconroy** [comment]
@VMDX Can we actually keep twitter and RSS in separate pull requests? The feed stuff is almost done

**Comment by vmdx** [comment]
Ready to go from my end.

**Comment by kyleconroy** [comment]
I'm not a fan of indenting the XML. Browsers will do that for us.

**Pull request merged**
