### PR TITLE
Pingdom polling

### PR DESCRIPTION
**Pull request by zsprackett**
This patch adds optional support for automagically updating statuses from pingdom using the pingdom API

### CODE REVIEW

**Comment by kyleconroy** [comment]
@zsprackett, awesome job. I'll work on merging this during the next week

**Comment by zsprackett** [comment]
@derferman sweet, let me know if you need any changes made.  thanks!

**Comment by kyleconroy** [comment]
@zsprackett Looked over the code and everything looks ok. However, I can't accept the pull request until there are tests for `check_pingdom` and `send_notifications`.

**Comment by kyleconroy** [comment]
I'm going to go ahead a close this, as no tests were ever written.

**Comment by bsdlp** [comment]
I'd like to take a poke at this.

**Pull request closed without merging**
