### PR TITLE
Tweets on events/notes

### PR DESCRIPTION
**Pull request by vmdx**
# Twitter Integration in Stashboard

This pull request allows users to optionally tweet upon adding a new Event or a note to a Service.

The configuration is in `settings.py` using [Single User Oauth](https://dev.twitter.com/docs/auth/oauth/single-user-with-examples).

```
# Twitter update settings
TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''
TWITTER_ACCESS_TOKEN = ''
TWITTER_ACCESS_TOKEN_SECRET = ''
TWITTER_HANDLE = 'stashboard_status'
```

And results in this interface if the `TWITTER_HANDLE` is set.

tweet on stashboard

### CODE REVIEW

**Comment by kyleconroy** [comment]
Small nitpik, but the question marks aren't needed for the checkboxes. 

On a larger scale, I think we should kick off a task on the task queue to tweet the status. This handles retries on errors and other situations. It also means we don't have to wait for the Twitter API to return a response.

**Comment by vmdx** [comment]
- Task queue implemented
- Removed question marks
- Moved tweet handler to `admin` namespace for security and to keep `api` clean
- Added tests to make sure tasks with '/admin/tweet' are added.

**Comment by kyleconroy** [comment]
Can you please pull in master? I'd love to get travis to run the tests for this branch before we merge

**Comment by vmdx** [comment]
Done. There was a conflict on `tests/test_rest_events.py` but it was trivial (imports).

**Pull request merged**
