### PR TITLE
Atom feed for service events and PubSubHubbub support

### PR DESCRIPTION
**Pull request by Kami**
This branch adds Atom feed for service events and PubSubHubbub support.

### CODE REVIEW

**Comment by kyleconroy** [comment]
@Kami, the code base has diverged significantly since this pull request. We also now have RSS feeds.

**Comment by Kami** [comment]
@kyleconroy Well, yeah. Next time it would be nice if someone would respond to the issues and comments sooner.

Just throwing code on Github and ignoring contributions for two years != responsible open-source.

**Comment by kyleconroy** [comment]
@Kami I completely agree, and it's totally my fault. I'm trying to make up for past mistakes.

**Comment by Kami** [comment]
@kyleconroy No problem, I was also kinda in a bad mood so I responded the way I did.

Next time, in a case like this, it would be nicer if you would say something along "Sorry for not having a look at this PR sooner, but I was busy with X and now the code has diverged significantly so I'm closing this PR, but ...".

**Comment by kyleconroy** [comment]
Yep, agreed. However, nothing excuses ignoring a pull request for two years. The only thing I can guarantee is that future pull requests won't meet the same fate.

**Pull request closed without merging**
